# Multiple Linear Regression

## Importing the libraries

In [75]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [76]:
dataset = pd.read_csv('Fish.csv')

X=dataset.drop('Weight',axis=1)
x = np.array(X.iloc[:, :-1].values)
Y=dataset[['Weight']]
y = np.array(Y.iloc[:, -1].values)

In [77]:

print(y)

[ 242.   290.   340.   363.   430.   450.   500.   390.   450.   500.
  475.   500.   500.   340.   600.   600.   700.   700.   610.   650.
  575.   685.   620.   680.   700.   725.   720.   714.   850.  1000.
  920.   955.   925.   975.   950.    40.    69.    78.    87.   120.
    0.   110.   120.   150.   145.   160.   140.   160.   169.   161.
  200.   180.   290.   272.   390.   270.   270.   306.   540.   800.
 1000.    55.    60.    90.   120.   150.   140.   170.   145.   200.
  273.   300.     5.9   32.    40.    51.5   70.   100.    78.    80.
   85.    85.   110.   115.   125.   130.   120.   120.   130.   135.
  110.   130.   150.   145.   150.   170.   225.   145.   188.   180.
  197.   218.   300.   260.   265.   250.   250.   300.   320.   514.
  556.   840.   685.   700.   700.   690.   900.   650.   820.   850.
  900.  1015.   820.  1100.  1000.  1100.  1000.  1000.   200.   300.
  300.   300.   430.   345.   456.   510.   540.   500.   567.   770.
  950.  1250.  1600.

## Encoding categorical data

In [78]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [79]:
print(x)

[[1.0 0.0 0.0 ... 25.4 30.0 11.52]
 [1.0 0.0 0.0 ... 26.3 31.2 12.48]
 [1.0 0.0 0.0 ... 26.5 31.1 12.3778]
 ...
 [0.0 0.0 0.0 ... 13.0 13.8 2.277]
 [0.0 0.0 0.0 ... 14.3 15.2 2.8728]
 [0.0 0.0 0.0 ... 15.0 16.2 2.9322]]


## Splitting the dataset into the Training set and Test set

In [80]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

## Training the Multiple Linear Regression model on the Training set

In [81]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

## Predicting the Test set results

In [82]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 424.91  390.  ]
 [  98.74    0.  ]
 [ 218.89  170.  ]
 [ 208.06  160.  ]
 [ 651.91  556.  ]
 [ 872.02  900.  ]
 [ 665.81  800.  ]
 [ 407.53  300.  ]
 [ 968.13  975.  ]
 [ 150.51  115.  ]
 [ 256.43  200.  ]
 [ 568.16  456.  ]
 [ 772.74 1000.  ]
 [1002.52 1000.  ]
 [-123.31   60.  ]
 [  16.15   78.  ]
 [ 137.74  145.  ]
 [1165.04 1600.  ]
 [ 174.09  130.  ]
 [ 723.39  720.  ]
 [-133.11   55.  ]
 [ 524.46  390.  ]
 [ 179.66  120.  ]
 [1323.93 1650.  ]
 [ -26.6    90.  ]
 [ 475.23  450.  ]
 [ 724.17  700.  ]
 [ 286.46  270.  ]
 [ 882.54  850.  ]
 [ -18.43    9.7 ]
 [ 578.77  650.  ]
 [ 158.34  110.  ]]
