# Convolutional Neural Network

### Importing the libraries

In [8]:
import tensorflow as tf
from keras.preprocessing.image import ImageDataGenerator

In [9]:
tf.__version__

'2.8.0'

## Data Preprocessing

### Preprocessing the Training set

In [10]:
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)
training_set = train_datagen.flow_from_directory('dataset/training_set',
                                                 target_size = (64, 64),
                                                 batch_size = 32,
                                                 class_mode = 'binary')

Found 8000 images belonging to 2 classes.


### Preprocessing the Test set

In [11]:
test_datagen = ImageDataGenerator(rescale = 1./255)
test_set = test_datagen.flow_from_directory('dataset/test_set',
                                            target_size = (64, 64),
                                            batch_size = 32,
                                            class_mode = 'binary')

Found 2000 images belonging to 2 classes.


## Building the CNN

### Initialising the CNN

In [14]:
cnn = tf.keras.models.Sequential()

###  Convolution

In [15]:
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu', input_shape=[64, 64, 3]))

### Pooling

In [16]:
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

### Adding a second convolutional layer

In [17]:
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

###  Flattening

In [18]:
cnn.add(tf.keras.layers.Flatten())

###  Full Connection

In [19]:
cnn.add(tf.keras.layers.Dense(units=128, activation='relu'))

###  Output Layer

In [20]:
cnn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

##  Training the CNN

### Compiling the CNN

In [21]:
cnn.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the CNN on the Training set and evaluating it on the Test set

In [22]:
cnn.fit(x = training_set, validation_data = test_set, epochs = 25)

Epoch 1/25
250/250 [==============================] - 56s 222ms/step - loss: 0.6621 - accuracy: 0.5911 - val_loss: 0.6224 - val_accuracy: 0.6405
Epoch 2/25
250/250 [==============================] - 47s 188ms/step - loss: 0.5948 - accuracy: 0.6786 - val_loss: 0.5714 - val_accuracy: 0.7055
Epoch 3/25
250/250 [==============================] - 60s 241ms/step - loss: 0.5558 - accuracy: 0.7129 - val_loss: 0.5304 - val_accuracy: 0.7425
Epoch 4/25
250/250 [==============================] - 61s 244ms/step - loss: 0.5287 - accuracy: 0.7308 - val_loss: 0.5039 - val_accuracy: 0.7535
Epoch 5/25
250/250 [==============================] - 57s 229ms/step - loss: 0.4968 - accuracy: 0.7563 - val_loss: 0.5538 - val_accuracy: 0.7195
Epoch 6/25
250/250 [==============================] - 53s 210ms/step - loss: 0.4920 - accuracy: 0.7616 - val_loss: 0.5043 - val_accuracy: 0.7650
Epoch 7/25
250/250 [==============================] - 45s 178ms/step - loss: 0.4659 - accuracy: 0.7805 - val_loss: 0.4735 - val_ac

##  Making a single prediction

In [27]:
import numpy as np
from keras.preprocessing import image
test_image = image.load_img('dataset/single_prediction/cat_or_dog_1.jpg', target_size = (64, 64))
#target_size set the image to the size of 64,64

test_image = image.img_to_array(test_image) 
print(test_image)
test_image = np.expand_dims(test_image, axis = 0)
print(test_image)
result = cnn.predict(test_image)
print(training_set.class_indices) #class_indices will give the class name and their respective encoding label.
if result[0][0] == 1:
  prediction = 'dog'
else:
  prediction = 'cat'

[[[ 54.  58.   7.]
  [ 58.  63.   9.]
  [ 64.  67.  10.]
  ...
  [136. 144.  71.]
  [140. 150.  77.]
  [139. 149.  78.]]

 [[ 48.  54.   6.]
  [ 51.  58.   7.]
  [ 58.  63.   9.]
  ...
  [129. 137.  64.]
  [139. 149.  78.]
  [141. 151.  80.]]

 [[ 48.  56.   7.]
  [ 48.  56.   7.]
  [ 54.  61.  10.]
  ...
  [123. 130.  63.]
  [136. 145.  80.]
  [140. 149.  82.]]

 ...

 [[ 46.  55.  12.]
  [ 42.  50.   9.]
  [ 38.  49.   9.]
  ...
  [239. 205. 170.]
  [235. 209. 186.]
  [229. 202. 173.]]

 [[ 50.  57.  15.]
  [ 42.  50.   9.]
  [ 44.  52.  11.]
  ...
  [234. 200. 162.]
  [236. 206. 178.]
  [234. 203. 174.]]

 [[ 53.  59.  13.]
  [ 43.  51.  10.]
  [ 49.  56.  12.]
  ...
  [231. 195. 159.]
  [235. 213. 190.]
  [233. 206. 179.]]]
[[[[ 54.  58.   7.]
   [ 58.  63.   9.]
   [ 64.  67.  10.]
   ...
   [136. 144.  71.]
   [140. 150.  77.]
   [139. 149.  78.]]

  [[ 48.  54.   6.]
   [ 51.  58.   7.]
   [ 58.  63.   9.]
   ...
   [129. 137.  64.]
   [139. 149.  78.]
   [141. 151.  80.]]

  [[

In [26]:
print(prediction)

dog
